<?php 
namespace Database\Seeders;

use Illuminate\Database\Seeder; 
use Illuminate\Support\Facades\Hash;
use Faker\Factory as Faker;
use App\Models\User; 
use Illuminate\Support\Facades\Validator;
use Helper;
use Image;

class UsersSeeder extends Seeder { 
    /** 
    * Run the database seeds. 
    * 
    * @return void */

 
   public function run() { 
     
           User::truncate(); 
           $faker = Faker::create();

            $name = $faker->hexColor();
           $users = [ 
            [ 
              'username' => 'support',
              'name' => 'Support',
              'family' => 'Center',
              'email' => "support@last.today",
              'password' => "support@last.today",
              'color' => $faker->hexColor(),
              'backgroundimage' => "assets/img/pexels-mart-production-7709297-min.jpg",
              'verify' => 1,
              'is_admin' => 1,
              'avatar' => "files/avatars/icons8-support-100.png",
              'profile_photo_path' => "files/avatars/icons8-support-100.png",
              'bio' => "Support Account - contact us with this account",
              'pv' => 0,
              'url' => null,
              'mobile' => null,
              'address' => null,
              'youtube' => null,
              'instagram' => null,
              'facebook' => null,
              'telegram' => null,
              'whatsapp' => null,
              'twitter' => null,
              'linkedin' => null,
              'tiktok' => null,
              'pinterest' => null,
              'snapchat' => null,
              'reddit' => null,
              'github' => null,
              'wikipedia' => null,
              'domain' => null,
              'logo' => null,
              'language' => null
            ],
            [ 
              'username' => 'demo',
              'name' => 'De',
              'family' => 'Mo',
              'email' => "demo@last.today",
              'password' => "demo@last.today",
              'color' => $faker->hexColor(),
              'backgroundimage' => 'assets/img/shop/digiday.jpeg',
              'verify' => 0,
              'is_admin' => null,
              'avatar' => "files/avatars/Multiavatar-627e908c5c9fc.png",
              'profile_photo_path' => "files/avatars/Multiavatar-627e908c5c9fc.png",
              'bio' => "Hi ,Im LT demo account you can login with this username and password demo@last.today",
              'pv' => 0,
              'url' => "http://demo.com/",
              'mobile' => "+4511111111",
              'address' => "Godthåbsvej 205, 2 16, 2720 København",
              'youtube' => "https://youtube.com/demo",
              'instagram' => "https://instagram.com/demo",
              'facebook' => "https://facebook.com/demo",
              'telegram' => "https://telegram.com/demo",
              'whatsapp' => "https://whatsapp.com/demo",
              'twitter' => "https://twitter.com/demo",
              'linkedin' => "https://linkedin.com/demo",
              'tiktok' => "https://tiktok.com/demo",
              'pinterest' => "https://pinterest.com/demo",
              'snapchat' => "https://snapchat.com/demo",
              'reddit' => "https://reddit.com/demo",
              'github' => "https://github.com/demo",
              'wikipedia' => "https://wikipedia.com/demo",
              'domain' => "https://tlt.buzz",
              'logo' => "/files/logo.png",
              'language' => 'en'
                        ],
            [ 
              'username' => 'anonymoususer',
              'name' => 'Anonymous',
              'family' => 'User',
              'email' => "nashenas@x.com",
              'password' => "nashenas@x.com",
              'color' => $faker->hexColor(),
              'backgroundimage' => 'assets/img/shop/security-6901712__340.jpeg',
              'verify' => 1,
              'is_admin' => null,
              'avatar' => "files/avatars/Multiavatar-627e908ed71a0.png",
              'profile_photo_path' => "files/avatars/Multiavatar-627e908ed71a0.png",
              'bio' => "This is an anonymous user who sends messages to non-member users.",
              'pv' => 0,
              'url' => null,
              'mobile' => null,
              'address' => null,
              'youtube' => null,
              'instagram' => null,
              'facebook' => null,
              'telegram' => null,
              'whatsapp' => null,
              'twitter' => null,
              'linkedin' => null,
              'tiktok' => null,
              'pinterest' => null,
              'snapchat' => null,
              'reddit' => null,
              'github' => null,
              'wikipedia' => null,
              'domain' => null,
              'logo' => null,
              'language' => null            ],
            [ 
              'username' => 'john503',
              'name' => 'john',
              'family' => '503',
              'email' => 'j0hn503@proton.me',
              'password' => 'LT!01',
              'color' => $faker->hexColor(),
              'backgroundimage' => 'files/backgroundimages/629a60dd24ce1diego-ph-BCuxVP5WEsU-unsplash-min.jpg',
              'verify' => 1,
              'is_admin' => 1,
              'avatar' => "files/avatars/farshid.png",
              'profile_photo_path' => "files/avatars/farshid.png",
              'bio' => 'Let us, with good work for ourselves and those around us, turn love on earth and in the sky, Hallelujah.',
              'pv' => 0,
              'url' => null,
              'mobile' => null,
              'address' => null,
              'youtube' => null,
              'instagram' => null,
              'facebook' => null,
              'telegram' => null,
              'whatsapp' => null,
              'twitter' => null,
              'linkedin' => null,
              'tiktok' => null,
              'pinterest' => null,
              'snapchat' => null,
              'reddit' => null,
              'github' => null,
              'wikipedia' => null,
              'domain' => null,
              'logo' => null,
              'language' => null            ],
            [ 
              'username' => 'amin',
              'name' => 'Amin',
              'family' => 'Khadivar',
              'email' => 'amin.khadivar@gmail.com',
              'password' => 'amin.khadivar@gmail.com',
              'color' => $faker->hexColor(),
              'backgroundimage' => null,
              'verify' => 1,
              'is_admin' => 0,
              'avatar' => "files/avatars/photo_2022-06-02_20-54-01.jpg",
              'profile_photo_path' => "files/avatars/photo_2022-06-02_20-54-01.jpg",
              'bio' => null,
              'pv' => 0,
              'url' => null,
              'mobile' => null,
              'address' => null,
              'youtube' => null,
              'instagram' => null,
              'facebook' => null,
              'telegram' => null,
              'whatsapp' => null,
              'twitter' => null,
              'linkedin' => null,
              'tiktok' => null,
              'pinterest' => null,
              'snapchat' => null,
              'reddit' => null,
              'github' => null,
              'wikipedia' => null,
              'domain' => null,
              'logo' => null,
              'language' => null            ],
            [ 
              'username' => 'mulle',
              'name' => 'Mulle',
              'family' => 'Saadi',
              'email' => 'buffalofood@yahoo.com',
              'password' => 'Mulle2513',
              'color' => $faker->hexColor(),
              'backgroundimage' => null,
              'verify' => 1,
              'is_admin' => 0,
              'avatar' => "files/avatars/photo_2022-06-02_20-53-58.jpg",
              'profile_photo_path' => "files/avatars/photo_2022-06-02_20-53-58.jpg",
              'bio' => null,
              'pv' => 0,
              'url' => null,
              'mobile' => null,
              'address' => null,
              'youtube' => null,
              'instagram' => null,
              'facebook' => null,
              'telegram' => null,
              'whatsapp' => null,
              'twitter' => null,
              'linkedin' => null,
              'tiktok' => null,
              'pinterest' => null,
              'snapchat' => null,
              'reddit' => null,
              'github' => null,
              'wikipedia' => null,
              'domain' => null,
              'logo' => null,
              'language' => null            ],
             

              [ 
                'username' => 'alidzr',
                'name' => 'Ali',
                'family' => 'Delzendehrooy',
                'email' => 'alidzr@gmail.com',
                'password' => 'alidzr@gmail.com',
                'color' => $faker->hexColor(),
                'backgroundimage' => null,
                'is_admin' => 0,
                'verify' => 1,
                'avatar' => "files/avatars/123465673_862864761120322_4418214126881615461_n.jpeg",
                'profile_photo_path' => "files/avatars/123465673_862864761120322_4418214126881615461_n.jpeg",
                'bio' => null,
                'pv' => 0,
                'url' => null,
                'mobile' => null,
                'address' => null,
                'youtube' => null,
                'instagram' => null,
                'facebook' => null,
                'telegram' => null,
                'whatsapp' => null,
                'twitter' => null,
                'linkedin' => null,
                'tiktok' => null,
                'pinterest' => null,
                'snapchat' => null,
                'reddit' => null,
                'github' => null,
                'wikipedia' => null,
                'domain' => null,
                'logo' => null,
                'language' => null
              ],
        
          ];
    
          foreach($users as $user)
          {
            $string = str_replace(' ', '_', $user['username']); // Replaces all spaces with hyphens.

            $username =  preg_replace('/[^A-Za-z0-9\-]/', '', $string); // Removes special chars.
            
              User::create([
               'username' =>  $username,
               'name' => $user['name'],
               'family' => $user['family'],
               'email' => $user['email'],
               'avatar' => $user['avatar'],
               'profile_photo_path' => $user['profile_photo_path'],
               'color' => $user['color'],
               'backgroundimage' => $user['backgroundimage'],
               'verify' => $user['verify'],
               'is_admin' => $user['is_admin'],
               'bio' => $user['bio'],
               'url' => $user['url'],
               'mobile' => $user['mobile'],
               'address' => $user['address'],
               'youtube' => $user['youtube'],
               'instagram' => $user['instagram'],
               'facebook' => $user['facebook'],
               'telegram' => $user['telegram'],
               'whatsapp' => $user['whatsapp'],
               'twitter' => $user['twitter'],
               'linkedin' => $user['linkedin'],
               'tiktok' => $user['tiktok'],
               'pinterest' => $user['pinterest'],
               'snapchat' => $user['snapchat'],
               'reddit' => $user['reddit'],
               'github' => $user['github'],
               'wikipedia' => $user['wikipedia'],
               'domain' => $user['domain'],
               'logo' => $user['logo'],
               'language' => $user['language'],
               'password' => Hash::make($user['password'])
             ]);
           }

    }
}